/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.dataProvdInfo.mapper;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.dataProvdInfo.entity.DataProvdInfo;

import java.util.List;
import java.util.Map;

/**
 * DataProvdInfo Mapper
 */
public interface DataProvdInfoMapper {

    DataProvdInfo getDataProvdInfo(Map<String, Object> params);

    int selectDataProvdInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectDataProvdInfoList(Map<String, Object> params);

    int insertDataProvdInfo(DataProvdInfo dataProvdInfo);

    int updateDataProvdInfo(DataProvdInfo dataProvdInfo);

    int updateDataProvdInfoDynamic(DataProvdInfo dataProvdInfo);

    int deleteDataProvdInfo(DataProvdInfo dataProvdInfo);

	int insertDownloadHistory(SimpleData dataProvdInfo);

	int deleteDuplicatedData();

}
