/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.dataProvdInfo.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.dataProvdInfo.entity.DataProvdInfo;
import kr.or.lx.rcic.modules.dataProvdInfo.mapper.DataProvdInfoMapper;
import kr.or.lx.rcic.modules.dataProvdInfo.service.DataProvdInfoService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  다운로드할 수 있는 데이터목록을 관리한다.  */
@Service
@Slf4j
public class DataProvdInfoServiceImpl implements DataProvdInfoService {

    @Autowired
    private DataProvdInfoMapper dataProvdInfoMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public DataProvdInfo getDataProvdInfo(Map<String, Object> params) throws Exception {
        log.debug("params: {}", params.toString()); // log 사용
        return dataProvdInfoMapper.getDataProvdInfo(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getDataProvdInfoList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = dataProvdInfoMapper.selectDataProvdInfoCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = dataProvdInfoMapper.selectDataProvdInfoList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);
        resultMap.put("totalCnt", cnt);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveDataProvdInfo(DataProvdInfo dataProvdInfo) throws Exception {

        // 저장 권한 검사 등..

        if (dataProvdInfo.hasPk()) {
            // 수정
            return updateDataProvdInfo(dataProvdInfo);
        } else {
            // 신규 등록
            return insertDataProvdInfo(dataProvdInfo);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertDataProvdInfo(DataProvdInfo dataProvdInfo) throws Exception {
        return dataProvdInfoMapper.insertDataProvdInfo(dataProvdInfo);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateDataProvdInfo(DataProvdInfo dataProvdInfo) throws Exception {
        return dataProvdInfoMapper.updateDataProvdInfo(dataProvdInfo);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateDataProvdInfoDynamic(DataProvdInfo dataProvdInfo) throws Exception {
        return dataProvdInfoMapper.updateDataProvdInfoDynamic(dataProvdInfo);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteDataProvdInfo(DataProvdInfo dataProvdInfo) throws Exception {
        return dataProvdInfoMapper.deleteDataProvdInfo(dataProvdInfo);
    }

	@Override
	public int insertDownloadHistory(SimpleData dataProvdInfo) {
		
		int cnt=0;
		
		try {
			cnt= dataProvdInfoMapper.insertDownloadHistory(dataProvdInfo);
		} catch (Exception e) {
			e.printStackTrace();
		}
		 return cnt;
	}

    /**
     * 중복데이터 제거
     */
    @Override
    @Transactional
    public int deleteDuplicatedData() {
        return dataProvdInfoMapper.deleteDuplicatedData();
    }


}