/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfo.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.modules.accdntInfo.entity.AccdntInfo;

/**
 *  유고정보(공사/사고)를 관리한다.  */
public interface AccdntInfoService {

    AccdntInfo getAccdntInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getAccdntInfoList(HttpServletRequest request) throws Exception;

    int saveAccdntInfo(AccdntInfo accdntInfo) throws Exception;

    int insertAccdntInfo(AccdntInfo accdntInfo) throws Exception;

    int updateAccdntInfo(AccdntInfo accdntInfo) throws Exception;

    int updateAccdntInfoDynamic(AccdntInfo accdntInfo) throws Exception;

    int deleteAccdntInfo(AccdntInfo accdntInfo) throws Exception;

}
