/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.user.service;

import kr.or.lx.rcic.modules.user.entity.AuthInfo;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 *  권한코드 정보를 관리한다.  */
public interface AuthInfoService {

    AuthInfo getAuthInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getAuthInfoList(HttpServletRequest request) throws Exception;

    Map<String, Object> getAuthInfoListAll() throws Exception;

    int saveAuthInfo(AuthInfo authInfo) throws Exception;

    int insertAuthInfo(AuthInfo authInfo) throws Exception;

    int updateAuthInfo(AuthInfo authInfo) throws Exception;

    int updateAuthInfoDynamic(AuthInfo authInfo) throws Exception;

    int deleteAuthInfo(AuthInfo authInfo) throws Exception;

    boolean existAuthNm(String authNm);

}
