/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.user.service;

import kr.or.lx.rcic.modules.user.entity.AuthDtl;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 *  권한별 상세정보를 관리한다.  */
public interface AuthDtlService {

    AuthDtl getAuthDtl(Map<String, Object> params) throws Exception;

    Map<String, Object> getAuthDtlList(HttpServletRequest request) throws Exception;

    int saveAuthDtl(AuthDtl authDtl) throws Exception;

    int insertAuthDtl(AuthDtl authDtl) throws Exception;

    int updateAuthDtl(AuthDtl authDtl) throws Exception;

    int updateAuthDtlDynamic(AuthDtl authDtl) throws Exception;

    int deleteAuthDtl(AuthDtl authDtl) throws Exception;

}
