/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisInfo.entity;

import lombok.Data;

/**
 *  수집된 입찰정보에서 도로변경정보로 예측된  정보를 관리한다.  */

@Data
public class AnalysisInfo {

    /**
     * 시퀀스
     */
    private Long seq;
    /**
     * 수집키
     */
    private Long resultno;
    /**
     * 공사현장지역명
     */
    private String cnstrtsitergnnm;
    /**
     * 입찰공고번호
     */
    private String bidntceno;
    /**
     * 입찰공고차수
     */
    private String bidntceord;
    /**
     * 공고종류명
     */
    private String ntcekindnm;
    /**
     * 공고기관명
     */
    private String ntceinsttnm;
    /**
     * 입찰공고일시
     */
    private String bidntcedt;
    /**
     * 시도코드
     */
    private String sidoCd;
    /**
     * 시군구코드
     */
    private String sggCd;
    /**
     * 읍면동코드
     */
    private String emdCd;
    /**
     * pnu
     */
    private String pnu;
    /**
     * 용도지역 코드
     */
    private String zoneCd;
    /**
     * 새주소 도로
     */
    private String roadCd;
    /**
     * poi cd
     */
    private String poiCd;
    /**
     * 연속지적 코드
     */
    private String cbndCd;
    /**
     * 분석일시
     */
    private String analysisDt;
    /**
     * 분석1
     */
    private String analysis1;
    /**
     * 분석2
     */
    private String analysis2;
    /**
     * 분석3
     */
    private String analysis3;
    /**
     * 분석4
     */
    private String analysis4;
    /**
     * 공고명
     */
    private String bidntcenm;
    /**
     * 관련번호
     */
    private String refno;
    /**
     * 공고URL
     */
    private String bidntcedtlurl;
    /**
     * 분석요소
     */
    private String analysisType;
    /**
     * 분석키워드
     */
    private String analysisWord;
    /**
     * Geomety
     */
    private String geom;
    /**
     * 표준노드링크 코드
     */
    private String moctCd;
    /**
     * UPIS_코드
     */
    private String upisCd;
    /**
     * 공사시작시기
     */
    private String anaysisStartDt;
    /**
     * 공사완료시기
     */
    private String anaysisEndDt;
    /**
     * 수집종료일
     */
    private String stdrDt;
    /**
     * 예측종료일
     */
    private String forecastEndDt;
    /**
     * 보정위치
     */
    private Object newGeom;
    /**
     * krris 관리대상 UID 맵핑
     */
    private String refKrrisUid;
    /**
     * 개소
     */
    private String attr1;
    /**
     * 계약종류
     */
    private String bidType;
    /**
     */
    private String attr2;
    /**
     * 위치예측신뢰도코드
     */
    private String locPrdtReliCd;
    /**
     * KRRIS 갱신여부
     */
    private String krrisUpdYn;
    /**
     * KRRIS 갱신일자
     */
    private String krrisUpdDt;
    /**
     * 도로 종류
     */
    private String roadType;

    public boolean hasPk() {
        return seq != null && seq != null && resultno != null;
    }

}