/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyStats.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.userMyStats.entity.UserMyStats;

/**
 *  업무사용자의 나의 통계목록 관리한다.  */
public interface UserMyStatsService {

    UserMyStats getUserMyStats(Map<String, Object> params) throws Exception;

    Map<String, Object> getUserMyStatsList(HttpServletRequest request) throws Exception;

    int insertUserMyStats(SimpleData simpleData) throws Exception;

    int updateUserMyStats(UserMyStats userMyStats) throws Exception;

    int deleteUserMyStats(SimpleData simpleData) throws Exception;

}
