/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.user.entity;

import lombok.Data;

import java.math.BigInteger;
import java.time.LocalDate;

/**
 *  권한별 상세정보를 관리한다.  */

@Data
public class AuthDtl {

    /**
     * 권한상세번호
     */
    private Long id;
    /**
     * 권한번호
     */
    private BigInteger authNo;
    /**
     * 메뉴번호
     */
    private BigInteger menuNo;
    /**
     * 권한상세구분
     */
    private String authDtlSe;
    /**
     * 권한상세내용
     */
    private String authDtlCn;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 수정일시
     */
    private LocalDate updtDt;

    public boolean hasPk() {
        return id != null;
    }

}