/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.user.entity;

import lombok.Data;

import java.time.LocalDate;

/**
 *  권한코드 정보를 관리한다.  */

@Data
public class AuthInfo {

    /**
     * 권한번호
     */
    private Long id;
    /**
     * 권한명
     */
    private String authNm;
    /**
     * 상태코드
     */
    private String sttus;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 수정일시
     */
    private LocalDate updtDt;
    /**
     * 등록아이디
     */
    private String registId;
    /**
     * 수정아이디
     */
    private String updtId;

    public boolean hasPk() {
        return id != null;
    }

}