/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.user.entity;

import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.Data;

/**
 *  ???(?????, ???)??? ????.  */

@Data
public class User {

    /**
     * 유저번호
     */
    private String userSeq;
    /**
     * 상태코드
     */
    private String status;
    /**
     * 상태코드
     */
    private String sttus;
    /**
     * 사용자이름
     */
    private String userNm;
    /**
     * 사용자아이디
     */
    private String userId;
    /**
     * 비밀번호
     */
    private String password;
    /**
     * 패스워드수정일시
     */
    private LocalDate lastLoginDt;
    /**
     * 최종로그인IP
     */
    private String lastLoginIp;
    /**
     * 등록자아이디
     */
    private String inptId;
    /**
     * 등록자아이디
     */
    private String registId;
    /**
     * 등록일시
     */
    private LocalDateTime inptDt;
    /**
     * 등록일시
     */
    private LocalDateTime registDt;
    /**
     * 수정자아이디
     */
    private String updtId;
    /**
     * 수정일시
     */
    private LocalDateTime updtDt;
    /**
     * 임시비밀번호
     */
    private String tmpPwd;
    /**
     * 시도횟수
     */
    private BigInteger tryCnt;
    /**
     * ???? ?? null: ????, y: ????
     */
    private String lockYn;
    /**
     * 접속IP
     */
    private String conectIp;
    /**
     * 연락전화번호
     */
    private String contactTelno;
    /**
     * 기관구분
     */
    private String insttSe;
    /**
     * 기관명
     */
    private String insttNm;
    /**
     * 이메일승인여부
     */
    private String emailConfmAt;
    /**
     * 이메일승인일시
     */
    private LocalDate emailConfmDt;
    /**
     * 권한번호
     */
    private BigInteger authNo;

    public boolean hasPk() {
        return userSeq != null && userSeq != null;
    }

}