/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisInfo.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.analysisInfo.entity.AnalysisInfo;
import kr.or.lx.rcic.modules.analysisInfo.mapper.AnalysisInfoMapper;
import kr.or.lx.rcic.modules.analysisInfo.service.AnalysisInfoService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  수집된 입찰정보에서 도로변경정보로 예측된  정보를 관리한다.  */
@Service
@Slf4j
public class AnalysisInfoServiceImpl implements AnalysisInfoService {

    @Autowired
    private AnalysisInfoMapper analysisInfoMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public AnalysisInfo getAnalysisInfo(Map<String, Object> params) throws Exception {
        log.debug("params: {}", params.toString()); // log 사용
        return analysisInfoMapper.getAnalysisInfo(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getAnalysisInfoList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = analysisInfoMapper.selectAnalysisInfoCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = analysisInfoMapper.selectAnalysisInfoList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveAnalysisInfo(AnalysisInfo analysisInfo) throws Exception {

        // 저장 권한 검사 등..

        if (analysisInfo.hasPk()) {
            // 수정
            return updateAnalysisInfo(analysisInfo);
        } else {
            // 신규 등록
            return insertAnalysisInfo(analysisInfo);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertAnalysisInfo(AnalysisInfo analysisInfo) throws Exception {
        return analysisInfoMapper.insertAnalysisInfo(analysisInfo);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateAnalysisInfo(AnalysisInfo analysisInfo) throws Exception {
        return analysisInfoMapper.updateAnalysisInfo(analysisInfo);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateAnalysisInfoDynamic(AnalysisInfo analysisInfo) throws Exception {
        return analysisInfoMapper.updateAnalysisInfoDynamic(analysisInfo);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteAnalysisInfo(AnalysisInfo analysisInfo) throws Exception {
        return analysisInfoMapper.deleteAnalysisInfo(analysisInfo);
    }

	@Override
	public int updateAnalysisInfoKrris(SimpleData simpleData) throws Exception {
		return analysisInfoMapper.updateAnalysisInfoKrris(simpleData);
	}

    /**
     * 파일생성용 데이터 조회
     * @param param
     * @return
     * @throws Exception
     */
    @Override
    public List<Map<String, Object>> getAnalysisInfoFileData(Map param) throws Exception {

        List<Map<String, Object>> list = analysisInfoMapper.getAnalysisInfoFileData(param);
        return list;
    }

    @Override
    public Map<String, Object> getAnalysisInfoFileDataList(Map param) throws Exception {

        int cnt = analysisInfoMapper.selectAnalysisInfoCnt(param);
        List<Map<String, Object>> list = analysisInfoMapper.getAnalysisInfoFileData(param);

        // 결과
        HashMap<String, Object> resultMap = new HashMap<>();
        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);
        resultMap.put("totalCnt", cnt);

        return resultMap;
    }

	@Override
	public Map<String, Object> getAnalysisInfoFileDataListMulti(Map param) throws Exception {
		 int cnt = analysisInfoMapper.selectAnalysisInfoCntMulti(param);
	        List<Map<String, Object>> list = analysisInfoMapper.getAnalysisInfoFileDataMulti(param);

	        // 결과
	        HashMap<String, Object> resultMap = new HashMap<>();
	        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
	        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);

	        resultMap.put("maxPageCnt", maxPageCnt);
	        resultMap.put("list", list);
	        resultMap.put("totalCnt", cnt);

	        return resultMap;
	}



}
