/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.entity;

import lombok.Data;

import java.time.LocalDate;

/**
 *  API 사용자의 차단정보를 관리한다.  */

@Data
public class ApiBlockInfo {

    /**
     * 일련넘버
     */
    private Long id;
    /**
     * API사용자번호
     */
    private Long apiUserNo;
    /**
     * 차단/해제구분
     */
    private String blockSe;
    /**
     * 차단/해제사유
     */
    private String blockReason;
    /**
     * 차단시작일
     */
    private String blockBeginDe;
    /**
     * 차단종료일
     */
    private String blockEndDe;
    /**
     * 해제일자
     */
    private String relisDe;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 등록아이디
     */
    private String registId;


    public boolean hasPk() {
        return id != null;
    }

    /**
     * 기관명
     */
    private String insttNm;

}