/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.entity;

import lombok.Data;

import java.time.LocalDate;

/**
 *  API로 데이터를 제공받는 사용자정보를 관리한다.  */

@Data
public class ApiUser {

    /**
     * API사용자번호
     */
    private Long id;
    /**
     * 사용자번호
     */
    private Long userSeq;
    /**
     * 기관명
     */
    private String insttNm;
    /**
     * 접속URL
     */
    private String conectUrl;
    /**
     * API인증키
     */
    private String apiCrtfcKey;
    /**
     * 상태코드
     */
    private String sttus;
    /**
     * 가입일자
     */
    private String srbde;
    /**
     * 차단여부
     */
    private String blockAt;
    /**
     * 본인인증CI
     */
    private String authCi;
    /**
     * 본인인증DI
     */
    private String authDi;
    /**
     * 등록아이디
     */
    private String registId;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 수정아이디
     */
    private String updtId;
    /**
     * 수정일시
     */
    private LocalDate updtDt;

    public boolean hasPk() {
        return id != null;
    }

}