/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.entity;

import lombok.Data;

import java.time.LocalDate;

/**
 *  API를 통해 제공된 사용내역을 관리한다.  */

@Data
public class ApiUseDtl {

    /**
     * API사용자번호
     */
    private Long apiUserNo;
    /**
     * API제공번호
     */
    private Long apiProvdNo;
    /**
     * 사용일자
     */
    private String useDe;
    /**
     * 사용시각
     */
    private String useHms;
    /**
     * 결과코드
     */
    private String resultCd;
    /**
     * 요청파라미터
     */
    private String requstParam;
    /**
     * 제공건수
     */
    private Integer provdCo;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 수정일시
     */
    private LocalDate updtDt;

    public boolean hasPk() {
        return apiUserNo != null && apiProvdNo != null && useDe != null && useHms != null;
    }

}