/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.snsAccountInfo.entity;

import lombok.Data;

/**
 *  수집대상이 되는 SNS 트위터 계정정보를 관리한다.  */

@Data
public class SnsAccountInfo {

    /**
     * 계정번호
     */
    private String accountNo;
    /**
     * 계정 아이디
     */
    private String accountId;
    /**
     * 계정 명
     */
    private String accountNm;
    /**
     * ???? 01:???, 02: ????, 03: ????
     */
    private String accountTy;
    /**
     * ????, y:??, n:???
     */
    private String useYn;
    /**
     * 타이머 일시
     */
    private String timer;

    public boolean hasPk() {
        return accountNo != null && accountNo != null;
    }

}