/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.dataProvdInfo.entity;

import lombok.Data;

/**
 *  다운로드할 수 있는 데이터목록을 관리한다.  */

@Data
public class DataProvdInfo {

    /**
     * 데이터제공번호
     */
    private Long id;
    /**
     * 데이터종류
     */
    private String dataKnd;
    /**
     * 데이터명
     */
    private String dataNm;
    /**
     * 데이터설명
     */
    private String dataDc;
    /**
     * 기준일자
     */
    private String stdrDe;
    /**
     * 파일위치
     */
    private String filePath;
    /**
     * 파일명
     */
    private String fileName;
    /**
     * 파일크기
     */
    private Long fileSize;
    /**
     * 파일유형
     */
    private String fileTy;
    /**
     * 공간좌표계
     */
    private String spceCntm;
    /**
     * 등록일시
     */
    private String registDt;
    /**
     * 수정일시
     */
    private String updtDt;

    public boolean hasPk() {
        return id != null;
    }

}