/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.modules.dataapi.entity.ApiProvdInfo;
import kr.or.lx.rcic.modules.dataapi.mapper.ApiProvdInfoMapper;
import kr.or.lx.rcic.modules.dataapi.service.ApiProvdInfoService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  API로 제공되는 정보를 관리한다.  */
@Service
@Slf4j
public class ApiProvdInfoServiceImpl implements ApiProvdInfoService {

    @Autowired
    private ApiProvdInfoMapper apiProvdInfoMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public ApiProvdInfo getApiProvdInfo(Map<String, Object> params) throws Exception {
        return apiProvdInfoMapper.getApiProvdInfo(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getApiProvdInfoList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = apiProvdInfoMapper.selectApiProvdInfoCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = apiProvdInfoMapper.selectApiProvdInfoList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);
        resultMap.put("totalCnt", cnt);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception {

        // 저장 권한 검사 등..

        if (apiProvdInfo.hasPk()) {
            // 수정
            return updateApiProvdInfo(apiProvdInfo);
        } else {
            // 신규 등록
            return insertApiProvdInfo(apiProvdInfo);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception {
        return apiProvdInfoMapper.insertApiProvdInfo(apiProvdInfo);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception {
        return apiProvdInfoMapper.updateApiProvdInfo(apiProvdInfo);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateApiProvdInfoDynamic(ApiProvdInfo apiProvdInfo) throws Exception {
        return apiProvdInfoMapper.updateApiProvdInfoDynamic(apiProvdInfo);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception {
        return apiProvdInfoMapper.deleteApiProvdInfo(apiProvdInfo);
    }

    /**
    * 사용여부 변경
    */
    @Override
    @Transactional
    public int changeUseYnApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception {
        return apiProvdInfoMapper.changeUseYnApiProvdInfo(apiProvdInfo);
    }

}
