/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.menu.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.modules.menu.entity.Menu;
import kr.or.lx.rcic.modules.menu.mapper.MenuMapper;
import kr.or.lx.rcic.modules.menu.service.MenuService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  RCIC 메뉴정보를 관리한다.  */
@Service
@Slf4j
public class MenuServiceImpl implements MenuService {

    @Autowired
    private MenuMapper menuMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public Menu getMenu(Map<String, Object> params) throws Exception {
        log.debug("params: {}", params.toString()); // log 사용
        return menuMapper.getMenu(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getMenuList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = menuMapper.selectMenuCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = menuMapper.selectMenuList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);

        return resultMap;
    }

    @Override
    public List<Menu> getAdminMenuList() {
        return menuMapper.selectAdminMenuList();
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveMenu(Menu menu) throws Exception {

        // 저장 권한 검사 등..

        if (menu.hasPk()) {
            // 수정
            return updateMenu(menu);
        } else {
            // 신규 등록
            return insertMenu(menu);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertMenu(Menu menu) throws Exception {
        return menuMapper.insertMenu(menu);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateMenu(Menu menu) throws Exception {
        return menuMapper.updateMenu(menu);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateMenuDynamic(Menu menu) throws Exception {
        return menuMapper.updateMenuDynamic(menu);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteMenu(Menu menu) throws Exception {
        return menuMapper.deleteMenu(menu);
    }

    /**
    * 사용여부 변경
    */
    @Override
    @Transactional
    public int changeUseYnMenu(Menu menu) throws Exception {
        return menuMapper.changeUseYnMenu(menu);
    }

}
