/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.mapper;

import kr.or.lx.rcic.modules.dataapi.entity.ApiBlockInfo;

import java.util.List;
import java.util.Map;

/**
 * ApiBlockInfo Mapper
 */
public interface ApiBlockInfoMapper {

    ApiBlockInfo getApiBlockInfo(Map<String, Object> params);

    int selectApiBlockInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectApiBlockInfoList(Map<String, Object> params);

    int insertApiBlockInfo(ApiBlockInfo apiBlockInfo);

    int updateApiBlockInfo(ApiBlockInfo apiBlockInfo);

    int updateApiBlockInfoDynamic(ApiBlockInfo apiBlockInfo);

    int deleteApiBlockInfo(ApiBlockInfo apiBlockInfo);

}
