/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.mapper;

import kr.or.lx.rcic.modules.dataapi.entity.ApiProvdInfo;

import java.util.List;
import java.util.Map;

/**
 * ApiProvdInfo Mapper
 */
public interface ApiProvdInfoMapper {

    ApiProvdInfo getApiProvdInfo(Map<String, Object> params);

    int selectApiProvdInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectApiProvdInfoList(Map<String, Object> params);

    int insertApiProvdInfo(ApiProvdInfo apiProvdInfo);

    int updateApiProvdInfo(ApiProvdInfo apiProvdInfo);

    int updateApiProvdInfoDynamic(ApiProvdInfo apiProvdInfo);

    int deleteApiProvdInfo(ApiProvdInfo apiProvdInfo);

    int changeUseYnApiProvdInfo(ApiProvdInfo apiProvdInfo);
}
