/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.mapper;

import kr.or.lx.rcic.modules.dataapi.entity.ApiUseDtl;

import java.util.List;
import java.util.Map;

/**
 * ApiUseDtl Mapper
 */
public interface ApiUseDtlMapper {

    ApiUseDtl getApiUseDtl(Map<String, Object> params);

    int selectApiUseDtlCnt(Map<String, Object> params);

    List<Map<String, Object>> selectApiUseDtlList(Map<String, Object> params);

    int insertApiUseDtl(ApiUseDtl apiUseDtl);

    int updateApiUseDtl(ApiUseDtl apiUseDtl);

    int updateApiUseDtlDynamic(ApiUseDtl apiUseDtl);

    int deleteApiUseDtl(ApiUseDtl apiUseDtl);

}
