/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.modules.dataapi.entity.ApiUser;

/**
 * ApiUser Mapper
 */
public interface ApiUserMapper {

    ApiUser getApiUser(Map<String, Object> params);

    int selectApiUserCnt(Map<String, Object> params);

    List<Map<String, Object>> selectApiUserList(Map<String, Object> params);

    int insertApiUser(HashMap<String, Object> param);

    int updateApiUser(ApiUser apiUser);

    int updateApiUserDynamic(ApiUser apiUser);

    int deleteApiUser(ApiUser apiUser);

}
