/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.menu.service;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.modules.menu.entity.Menu;

/**
 *  RCIC 메뉴정보를 관리한다.  */
public interface MenuService {

    Menu getMenu(Map<String, Object> params) throws Exception;

    Map<String, Object> getMenuList(HttpServletRequest request) throws Exception;

    List<Menu> getAdminMenuList();

    int saveMenu(Menu menu) throws Exception;

    int insertMenu(Menu menu) throws Exception;

    int updateMenu(Menu menu) throws Exception;

    int updateMenuDynamic(Menu menu) throws Exception;

    int deleteMenu(Menu menu) throws Exception;

    int changeUseYnMenu(Menu menu) throws Exception;

}
