/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.code.entity;

import lombok.Data;
import org.apache.commons.lang3.StringUtils;

/**
 *  공통코드그룹정보를 관리한다.  */

@Data
public class CodeGroup {

    /**
     * 그룹코드
     */
    private String groupCode;
    /**
     * 그룹코드명
     */
    private String groupNm;
    /**
     * 코드설명
     */
    private String codeDc;
    /**
     * 사용여부
     */
    private String useYn;
    /**
     * 비고
     */
    private String rm;
    /**
     * 등록자아이디
     */
    private String registId;
    /**
     * 등록일시
     */
    private String registDt;

    public boolean hasPk() {
        return StringUtils.isNotEmpty(groupCode);
    }

}