/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisLocHist.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.Data;

/**
 *  도로변경예측정보의 위치수정이력을 관리한다.  */

@Data
public class AnalysisLocHist {

    /**
     * 시퀀스
     */
    private Long seq;
    /**
     * 일련번호
     */
    private Long serNo;
    /**
     * 변경일시
     */
    private LocalDate chgDt;
    /**
     * 변경방법
     */
    private String chgResnCd;
    /**
     * 변경방법설명
     */
    private String chgResnDc;
    /**
     * 위치공간정보
     */
    private Object geom;
    /**
     * 위치예측신뢰도코드
     */
    private String locPrdtReliCd;
    /**
     * 등록일시
     */
    private LocalDateTime registDt;
    /**
     * 등록아이디
     */
    private String registId;

    public boolean hasPk() {
        return seq != null && serNo != null;
    }

}