/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.snsAccountInfo.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.modules.snsAccountInfo.entity.SnsAccountInfo;

/**
 * SnsAccountInfo Mapper
 */
public interface SnsAccountInfoMapper {

    SnsAccountInfo getSnsAccountInfo(Map<String, Object> params);

    int selectSnsAccountInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectSnsAccountInfoList(Map<String, Object> params);

    int insertSnsAccountInfo(SnsAccountInfo snsAccountInfo);

    int updateSnsAccountInfo(SnsAccountInfo snsAccountInfo);

    int updateSnsAccountInfoDynamic(SnsAccountInfo snsAccountInfo);

    int deleteSnsAccountInfo(SnsAccountInfo snsAccountInfo);

    int changeUseYnSnsAccountInfo(SnsAccountInfo snsAccountInfo);
}
