/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisInfo.mapper;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.analysisInfo.entity.AnalysisInfo;
import org.apache.ibatis.cache.CacheException;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AnalysisInfo Mapper
 */
public interface AnalysisInfoMapper {

    AnalysisInfo getAnalysisInfo(Map<String, Object> params);

    int selectAnalysisInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAnalysisInfoList(Map<String, Object> params);

    int insertAnalysisInfo(AnalysisInfo analysisInfo);

    int updateAnalysisInfo(AnalysisInfo analysisInfo);

    int updateAnalysisInfoDynamic(AnalysisInfo analysisInfo);

    int deleteAnalysisInfo(AnalysisInfo analysisInfo);

	int updateAnalysisInfoKrris(SimpleData simpleData);

	int getAnalysisInfoFileDataCnt(Map param);

	List<Map<String, Object>> getAnalysisInfoFileData(Map param);

	void updateLocPrdtReliCd(SimpleData simpleData);
	
	List<Map<String, Object>> getAnalysisDetailCbnd(HashMap<String, Object> param);
	
	List<Map<String, Object>> getAnalysisDetailDevelop(HashMap<String, Object> param);
	
	List<Map<String, Object>> getAnalysisDetailPoi(HashMap<String, Object> param);

	List<Map<String, Object>> getAnalysisDetailRoad(HashMap<String, Object> param);

	List<Map<String, Object>> getAnalysisInfoFileDataMulti(Map param);

	int selectAnalysisInfoCntMulti(Map<String, Object> params);

	List<Map<String, Object>> selectRoadLayerList(String resultNo);

	List<Map<String, Object>> selectRoadInfoList(String resultno);

	Map<String, Object> getRoadLayerImg(String layNm);

	Map<String, Object> selectRoadLayerDataFlag(Map<String, Object> dataMap);

	List<Map<String, Object>> selectRoadLayerDataList(Map<String, Object> dataMap);

	int getlocChangeCnt(String resultno);

	List<Map<String, Object>> selectRoadInfoHistList(String resultno);

	int insertCalsDataToRcic(Map<String, Object> dataMap) ;


}
