/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyArea.entity;

import java.math.BigInteger;
import java.time.LocalDate;

import lombok.Data;

/**
 *  나의관심지역  */

@Data
public class UserMyArea {

    /**
     * 관심지역번호
     */
    private Long myAreaNo;
    /**
     * 사용자번호
     */
    private String userSeq;
    /**
     * 관심지역유형
     */
    private String myAreaTy;
    /**
     * 시군구코드
     */
    private String sggCd;
    /**
     * 최소X좌표
     */
    private BigInteger minX;
    /**
     * 업무사용자의 관심지역을 관리한다.
     */
    private BigInteger minY;
    /**
     * 최대X좌표
     */
    private BigInteger maxX;
    /**
     * 최대Y좌표
     */
    private BigInteger maxY;
    /**
     * 지도줌레벨
     */
    private BigInteger zoomLv;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 등록아이디
     */
    private String registId;
    /**
     * 수정일시
     */
    private LocalDate updtDt;
    /**
     * 수정아이디
     */
    private String updtId;

    public boolean hasPk() {
        return myAreaNo != null && userSeq != null;
    }

}