/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyArea.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.userMyArea.entity.UserMyArea;

/**
 *  나의관심지역  */
public interface UserMyAreaService {

    UserMyArea getUserMyArea(Map<String, Object> params) throws Exception;

    Map<String, Object> getUserMyAreaList(HttpServletRequest request) throws Exception;

    int insertUserMyArea(SimpleData simpleData) throws Exception;

    int updateUserMyArea(UserMyArea userMyArea) throws Exception;

    int updateUserMyAreaDynamic(UserMyArea userMyArea) throws Exception;

    int deleteUserMyArea(SimpleData simpleData) throws Exception;

}
