/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisLocHist.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.analysisLocHist.entity.AnalysisLocHist;

/**
 *  도로변경예측정보의 위치수정이력을 관리한다.  */
public interface AnalysisLocHistService {

    AnalysisLocHist getAnalysisLocHist(Map<String, Object> params) throws Exception;

    Map<String, Object> getAnalysisLocHistList(HttpServletRequest request) throws Exception;

    int insertAnalysisLocHist(SimpleData simpleData) throws Exception;

    int updateAnalysisLocHist(AnalysisLocHist analysisLocHist) throws Exception;

    int updateAnalysisLocHistDynamic(AnalysisLocHist analysisLocHist) throws Exception;

    int deleteAnalysisLocHist(AnalysisLocHist analysisLocHist) throws Exception;
    
    int updateChangeLocation(SimpleData simpleData) throws Exception;
    
    String getChnage_yn(String resultno) throws Exception;

}
