/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyArea.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.user.User;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.userMyArea.entity.UserMyArea;
import kr.or.lx.rcic.modules.userMyArea.mapper.UserMyAreaMapper;
import kr.or.lx.rcic.modules.userMyArea.service.UserMyAreaService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  나의관심지역  */
@Service
@Slf4j
public class UserMyAreaServiceImpl implements UserMyAreaService {

    @Autowired
    private UserMyAreaMapper userMyAreaMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public UserMyArea getUserMyArea(Map<String, Object> params) throws Exception {
        log.debug("params: {}", params.toString()); // log 사용
        return userMyAreaMapper.getUserMyArea(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getUserMyAreaList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);
        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal(); //로그인 사용자 정보 조회
        param.put("userSeq", user.getUserNo());
        
        int cnt = userMyAreaMapper.selectUserMyAreaCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = userMyAreaMapper.selectUserMyAreaList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);
        resultMap.put("cnt", cnt);

        return resultMap;
    }


    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertUserMyArea(SimpleData simpleData) throws Exception {
    	 User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal(); //로그인 사용자 정보 조회
    	 simpleData.put("registId", user.getUserid());
    	 simpleData.put("updtId", user.getUserid());
    	 simpleData.put("userSeq", user.getUserNo());
         
        return userMyAreaMapper.insertUserMyArea(simpleData);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateUserMyArea(UserMyArea userMyArea) throws Exception {
        return userMyAreaMapper.updateUserMyArea(userMyArea);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateUserMyAreaDynamic(UserMyArea userMyArea) throws Exception {
        return userMyAreaMapper.updateUserMyAreaDynamic(userMyArea);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteUserMyArea(SimpleData simpleData) throws Exception {
    	User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal(); //로그인 사용자 정보 조회
	   	simpleData.put("registId", user.getUserid());
	   	simpleData.put("userSeq", user.getUserNo());
	   	
	   	String[] chkMyAreaNoArr = String.valueOf(simpleData.get("chkMyAreaNoStr")).split(",");
        
	   	simpleData.put("chkMyAreaNoArr",chkMyAreaNoArr);
	   	
        return userMyAreaMapper.deleteUserMyArea(simpleData);
    }



}
