/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.menu.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.modules.menu.entity.Menu;

/**
 * Menu Mapper
 */
public interface MenuMapper {

    Menu getMenu(Map<String, Object> params);

    int selectMenuCnt(Map<String, Object> params);

    List<Map<String, Object>> selectMenuList(Map<String, Object> params);

    List<Menu> selectAdminMenuList();

    int insertMenu(Menu menu);

    int updateMenu(Menu menu);

    int updateMenuDynamic(Menu menu);

    int deleteMenu(Menu menu);

    int changeUseYnMenu(Menu menu);
}
