/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.menu.entity;

import java.util.List;

import lombok.Data;

/**
 *  RCIC 메뉴정보를 관리한다.  */

@Data
public class Menu {

    /**
     * 메뉴번호
     */
    private Long id;
    /**
     * 상위메뉴번호
     */
    private Long upMenuNo;
    /**
     * 메뉴명
     */
    private String menuNm;
    /**
     * 메뉴코드
     */
    private String menuCd;
    /**
     * 사용여부
     */
    private String useYn;
    /**
     * 등록일시
     */
    private String registDt;
    /**
     * 등록아이디
     */
    private String registId;
    /**
     * 수정일시
     */
    private String updtDt;
    /**
     * 수정아이디
     */
    private String updtId;

    public boolean hasPk() {
        return id != null;
    }

    private List<Menu> childMenuList;

}