/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyArea.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.userMyArea.entity.UserMyArea;

/**
 * UserMyArea Mapper
 */
public interface UserMyAreaMapper {

    UserMyArea getUserMyArea(Map<String, Object> params);

    int selectUserMyAreaCnt(Map<String, Object> params);

    List<Map<String, Object>> selectUserMyAreaList(Map<String, Object> params);

    int insertUserMyArea(SimpleData simpleData);

    int updateUserMyArea(UserMyArea userMyArea);

    int updateUserMyAreaDynamic(UserMyArea userMyArea);

    int deleteUserMyArea(SimpleData simpleData);

}
