/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/controller/Controller.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfo.controller;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.frmwrk.web.BaseController;
import kr.or.lx.rcic.modules.accdntInfo.entity.AccdntInfo;
import kr.or.lx.rcic.modules.accdntInfo.service.AccdntInfoService;
import lombok.extern.slf4j.Slf4j;

/**
 *  유고정보(공사/사고)를 관리한다.  */
@Controller
@Slf4j
@RequestMapping("/rcic")
public class AccdntInfoController extends BaseController {

    @Autowired
    private AccdntInfoService accdntInfoService;

    // api

    /**
     * 단건 조회
     */
    @RequestMapping("/accdntInfo/getAccdntInfo")
    @ResponseBody
    public AccdntInfo getAccdntInfo(HttpServletRequest request, @RequestParam Map params) throws Exception {
        SimpleData simpleData = getSimpleData(request);
        return accdntInfoService.getAccdntInfo(simpleData);
    }

    /**
     * 목록 조회
     */
    @RequestMapping("/accdntInfo/getAccdntInfoList")
    @ResponseBody
    public Map<String, Object> getAccdntInfoList(HttpServletRequest request) throws Exception {
        return accdntInfoService.getAccdntInfoList(request);
    }

    /**
     * 등록
     */
    @PostMapping("/accdntInfo/insertAccdntInfo")
    @ResponseBody
    public int insertAccdntInfo(HttpServletRequest request, @RequestBody AccdntInfo accdntInfo) throws Exception {
        return accdntInfoService.saveAccdntInfo(accdntInfo);
    }

    /**
     * 수정
     */
    @PostMapping("/accdntInfo/updateAccdntInfo")
    @ResponseBody
    public int updateAccdntInfo(HttpServletRequest request, @RequestBody AccdntInfo accdntInfo) throws Exception {
        return accdntInfoService.saveAccdntInfo(accdntInfo);
    }

    /**
     * 동적 수정
     */
    @PostMapping("/accdntInfo/patchAccdntInfo")
    @ResponseBody
    public int patchAccdntInfo(HttpServletRequest request, @RequestBody AccdntInfo accdntInfo) throws Exception {
        return accdntInfoService.saveAccdntInfo(accdntInfo);
    }

    /**
     * 삭제
     */
    @PostMapping("/accdntInfo/deleteAccdntInfo")
    @ResponseBody
    public int deleteAccdntInfo(HttpServletRequest request, @RequestBody AccdntInfo accdntInfo) throws Exception {
        return accdntInfoService.deleteAccdntInfo(accdntInfo);
    }

}
