/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfoApi.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.modules.accdntInfoApi.entity.AccdntInfoApi;

/**
 *  */
public interface AccdntInfoApiService {

    AccdntInfoApi getAccdntInfoApi(Map<String, Object> params) throws Exception;

    Map<String, Object> getAccdntInfoApiList(HttpServletRequest request) throws Exception;

    int saveAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception;

    int insertAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception;

    int updateAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception;

    int updateAccdntInfoApiDynamic(AccdntInfoApi accdntInfoApi) throws Exception;

    int deleteAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception;

}
