/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyStats.entity;

import java.math.BigInteger;
import java.time.LocalDate;

import lombok.Data;

/**
 *  업무사용자의 나의 통계목록 관리한다.  */

@Data
public class UserMyStats {

    /**
     * 사용자번호
     */
    private String userSeq;
    /**
     * 통계목록구분
     */
    private String statsListSe;
    /**
     * 통계차트구분
     */
    private String statsChrtSe;
    /**
     * 표시순서
     */
    private BigInteger dispOrder;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * 등록아이디
     */
    private String registId;
    /**
     * 수정일시
     */
    private LocalDate updtDt;
    /**
     * 수정아이디
     */
    private String updtId;

    public boolean hasPk() {
        return userSeq != null && statsListSe != null && statsChrtSe != null;
    }

}