/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfoApi.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.modules.accdntInfoApi.entity.AccdntInfoApi;
import kr.or.lx.rcic.modules.accdntInfoApi.mapper.AccdntInfoApiMapper;
import kr.or.lx.rcic.modules.accdntInfoApi.service.AccdntInfoApiService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  */
@Service
@Slf4j
public class AccdntInfoApiServiceImpl implements AccdntInfoApiService {

    @Autowired
    private AccdntInfoApiMapper accdntInfoApiMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public AccdntInfoApi getAccdntInfoApi(Map<String, Object> params) throws Exception {
        return accdntInfoApiMapper.getAccdntInfoApi(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getAccdntInfoApiList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = accdntInfoApiMapper.selectAccdntInfoApiCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = accdntInfoApiMapper.selectAccdntInfoApiList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception {

        // 저장 권한 검사 등..

        if (accdntInfoApi.hasPk()) {
            // 수정
            return updateAccdntInfoApi(accdntInfoApi);
        } else {
            // 신규 등록
            return insertAccdntInfoApi(accdntInfoApi);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception {
        return accdntInfoApiMapper.insertAccdntInfoApi(accdntInfoApi);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception {
        return accdntInfoApiMapper.updateAccdntInfoApi(accdntInfoApi);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateAccdntInfoApiDynamic(AccdntInfoApi accdntInfoApi) throws Exception {
        return accdntInfoApiMapper.updateAccdntInfoApiDynamic(accdntInfoApi);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteAccdntInfoApi(AccdntInfoApi accdntInfoApi) throws Exception {
        return accdntInfoApiMapper.deleteAccdntInfoApi(accdntInfoApi);
    }

}
