/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfoApi.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.modules.accdntInfoApi.entity.AccdntInfoApi;

/**
 * AccdntInfoApi Mapper
 */
public interface AccdntInfoApiMapper {

    AccdntInfoApi getAccdntInfoApi(Map<String, Object> params);

    int selectAccdntInfoApiCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAccdntInfoApiList(Map<String, Object> params);

    int insertAccdntInfoApi(AccdntInfoApi accdntInfoApi);

    int updateAccdntInfoApi(AccdntInfoApi accdntInfoApi);

    int updateAccdntInfoApiDynamic(AccdntInfoApi accdntInfoApi);

    int deleteAccdntInfoApi(AccdntInfoApi accdntInfoApi);

}
