/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.user.mapper;

import egovframework.rte.psl.dataaccess.mapper.Mapper;
import kr.or.lx.rcic.modules.user.entity.AuthInfo;

import java.util.List;
import java.util.Map;

/**
 * AuthInfo Mapper
 */
@Mapper
public interface AuthInfoMapper {

    AuthInfo getAuthInfo(Map<String, Object> params);

    int selectAuthInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAuthInfoList(Map<String, Object> params);

    int insertAuthInfo(AuthInfo authInfo);

    int updateAuthInfo(AuthInfo authInfo);

    int updateAuthInfoDynamic(AuthInfo authInfo);

    int deleteAuthInfo(AuthInfo authInfo);

    boolean existAuthNm(String authNm);

}
