/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.user.mapper;

import kr.or.lx.rcic.modules.user.entity.AuthDtl;

import java.util.List;
import java.util.Map;

/**
 * AuthDtl Mapper
 */
public interface AuthDtlMapper {

    AuthDtl getAuthDtl(Map<String, Object> params);

    int selectAuthDtlCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAuthDtlList(Map<String, Object> params);

    int insertAuthDtl(AuthDtl authDtl);

    int updateAuthDtl(AuthDtl authDtl);

    int updateAuthDtlDynamic(AuthDtl authDtl);

    int deleteAuthDtl(AuthDtl authDtl);

    boolean existAuthDtl(AuthDtl authDtl);

}
