/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

/**
 *  SNS(트위터)에서 수집된 정보를 관리한다.  */

@Data
public class SolrSnsInfo {
	@Field
	private int numFound;
    /**
     * sns_no
     */
	@Field
    private String sns_no;
    /**
     * 1: twitter, 2: facebook
     */
	@Field
    private String sns_type;
    /**
     * 키워드
     */
	@Field
    private String sns_keyword;
    /**
     * 컨텐츠
     */
	@Field
    private String sns_content;
    /**
     * sns_계정
     */
	@Field
    private String sns_account;
    /**
     * sns_url
     */
	@Field
    private String sns_url;
    /**
     * sns_수집시각
     */
	@Field
    private String sns_regist_dt;
    /**
     * sns_글등록시간
     */
	@Field
    private String sns_create_dt;
    /**
     * sns_profile_img
     */
	@Field
    private String sns_profile_img;
    /**
     * sns_ID
     */
	@Field
    private String sns_id;
    /**
     * sns_프로필 백그라운드 컬러
     */
	@Field
    private String sns_profile_background_color;
    /**
     * sns_프로필 텍스트 컬러
     */
	@Field
    private String sns_profile_text_color;
    /**
     * sns_profile_https_img
     */
	@Field
    private String sns_profile_https_img;
    /**
     * sns_name
     */
	@Field
    private String sns_name;
    /**
     * sns_description
     */
	@Field
    private String sns_description;
    /**
     * sns수집 기준일
     */
	@Field
    private String stdr_dt;
    /**
     * 타이머
     */
	@Field
    private String sns_timer;
    /**
     * UTM-K X좌표
     */
	@Field
    private String utmk_x;
    /**
     * UTM-K Y좌표
     */
	@Field
    private String utmk_y;
	
	@Field
    private String geom;
	
	@Field
    private String geo_geom;

	@Field
    private String geo_wkt;

}