/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

/**
 *  수집된 입찰정보에서 도로변경정보로 예측된  정보를 관리한다.  */

@Data
public class SolrAnalysisInfo {

	@Field
	private int numFound;
    /**
     * 시퀀스
     */
	@Field
    private String seq;
    /**
     * 수집키
     */
	@Field
    private String resultno;
    /**
     * 공사현장지역명
     */
	@Field
    private String cnstrtsitergnnm;
    /**
     * 입찰공고번호
     */
	@Field
    private String bidntceno;
    /**
     * 입찰공고차수
     */
	@Field
    private String bidntceord;
    /**
     * 공고종류명
     */
	@Field
    private String ntcekindnm;
    /**
     * 공고기관명
     */
	@Field
    private String ntceinsttnm;
    /**
     * 입찰공고일시
     */
	@Field
    private String bidntcedt;
    /**
     * 시도코드
     */
	@Field
    private String sido_cd;
    /**
     * 시군구코드
     */
	@Field
    private String sgg_cd;
    /**
     * 읍면동코드
     */
	@Field
    private String emd_cd;
	
	@Field
    private String analysis_dt;
   
	@Field
    private String bidntcenm;
	
	@Field
    private String refno;
	
	@Field
    private String bidntcedtlurl;
	
	@Field
    private String analysis_type;
	
	@Field
    private String analysis_word;
	
	@Field
    private String stdr_dt;
	
	@Field
    private String forecast_st_dt;
	
	@Field
    private String forecast_end_dt;
	
	@Field
    private String place_cnt;
	
	@Field
    private String bid_type;
	
	@Field
    private String ref_krris_uid;
	
	@Field
    private String loc_prdt_reli_cd;
	
	@Field
    private String krris_upd_yn;
	
	@Field
    private String krris_upd_dt;
	
	@Field
    private String const_road_clss;
	
	@Field
    private String const_road_nm;
	
	@Field
    private String loc_ref_dict_nm;
	
	@Field
    private String loc_ref_no;
	
	@Field
	private String sido_nm;
	
	@Field
	private String ntceinsttcd;
	
	@Field
	private String bdgtamt;
	
	@Field
	private String bidmethdnm;
	
	@Field
	private String search_word;
	
	@Field
	private String presmptprce; 
	
	@Field
	private String asignbdgtamt;
	
	@Field
	private String dminsttnm;
	
	@Field
	private String dminsttcd;
	
	@Field
	private String sido_thin_nm;
	
	@Field
	private String tot_cntr_ct_amt;
	
	@Field
	private String ttal_ccmplt_date;
	
	@Field
	private String max_cntr_ctcncls_date;
	
	@Field
	private String thtm_ccmplt_date;
	
	@Field
	private String tht_mcnt_rct_amt;
	
	@Field
	private String cbgn_date;
	
	@Field
	private String min_cntr_ctcncls_date;
	
	@Field
	private String coplist;
	

}