/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

/**
 *  SNS(트위터)에서 수집된 정보를 관리한다.  */

@Data
public class SolrSnsLocInfo {
	@Field
	private String loc_ref_dic;
    /**
     * sns_no
     */
	@Field
    private String sns_no;
    /**
     * sns수집 기준일
     */
	@Field
    private String stdr_dt;
	
	@Field
    private String geom_wkt;
	
	@Field
    private String geom;
	
	@Field
    private String geo_geom;
	
	@Field
    private String sns_content;
	
	@Field
    private String seq;
	
	@Field
    private String loc_ref_no;
}