/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

@Data
public class SolrAnalysisRoadInfo {

    /**
     * 시도코드
     */
	@Field
    private String sido_cd;
    /**
     * 시군구코드
     */
	@Field
    private String sgg_cd;
    /**
     * 읍면동코드
     */
	@Field
    private String emd_cd;
    /**
     * 도로요소코드
     */
	@Field
    private String road_ty_cd;
    /**
     */
	@Field
    private String road_ty_nm;
    /**
     * 분석일자
     */
	@Field
    private String stdr_dt;
    /**
     * 수집번호
     */
	@Field
    private String resultno;
	
	@Field
    private String bidntcedt;
	
	private String base64_attr1;
	private String base64_attr2;	

}