/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

/**
 *  G2B에서 수집된 데이터를 관리한다. (G2B 원천데이터)  */

@Data
public class SolrG2bGroupResult {

	@Field
	private int numFound;
	 
	@Field
	private String stdr_week;

}