/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.search.dto;

import java.math.BigInteger;
import java.time.LocalDateTime;

import org.apache.solr.client.solrj.beans.Field;

import lombok.Data;

/**
 *  G2B에서 수집된 데이터를 관리한다. (G2B 원천데이터)  */

@Data
public class SolrG2bResultInfo {

	@Field
	private int numFound;
	/**
     * 수집번호
     */
    @Field
    private String resultno;
    /**
     * 입찰공고번호
     */
    @Field
    private String bidntceno;
    /**
     * 입찰공고차수
     */
    @Field
    private String bidntceord;
    /**
     * 재공고여부
     */
    @Field
    private String rentceyn;
    /**
     * 등록유형명[조달청 또는 나라장터 자체 공고건]
     */
    @Field
    private String rgsttynm;
    /**
     * 공고종류명
     */
    @Field
    private String ntcekindnm;
    /**
     * 국제입찰여부
     */
    @Field
    private String intrbidyn;
    /**
     * 입찰공고일시
     */
    @Field
    private String bidntcedt;
    /**
     * 참조번호
     */
    @Field
    private String refno;
    /**
     * 입찰공고명
     */
    @Field
    private String bidntcenm;
    /**
     * 공고기관코드
     */
    @Field
    private String ntceinsttcd;
    /**
     * 공고기관명
     */
    @Field
    private String ntceinsttnm;
    /**
     * 수요기관코드
     */
    @Field
    private String dminsttcd;
    /**
     * 수요기관명
     */
    @Field
    private String dminsttnm;
    /**
     * 입찰방식명
     */
    @Field
    private String bidmethdnm;
    /**
     * 계약체결방법명
     */
    @Field
    private String cntrctcnclsmthdnm;
    /**
     * 공고기관담당자명
     */
    @Field
    private String ntceinsttofclnm;
    /**
     * 공고기관담당자전화번호
     */
    @Field
    private String ntceinsttofcltelno;
    /**
     * 공고기관담당자이메일주소
     */
    @Field
    private String ntceinsttofclemailadrs;
    /**
     * 집행관명
     */
    @Field
    private String exctvnm;
    /**
     * 입찰참가자격등록마감일시
     */
    @Field
    private String bidqlfctrgstdt;
    /**
     * 공동수급협정서접수방식
     */
    @Field
    private String cmmnspldmdagrmntrcptdocmethd;
    /**
     * 공동수급협정마감일시
     */
    @Field
    private String cmmnspldmdagrmntclsedt;
    /**
     * 공동수급업체지역제한여부
     */
    @Field
    private String cmmnspldmdcorprgnlmtyn;
    /**
     * 입찰개시일시
     */
    @Field
    private String bidbegindt;
    /**
     * 입찰마감일시
     */
    @Field
    private String bidclsedt;
    /**
     * 개찰일시
     */
    @Field
    private String opengdt;
    /**
     * 공고규격서URL1
     */
    @Field
    private String ntcespecdocurl1;
    /**
     * 공고규격서URL2
     */
    @Field
    private String ntcespecdocurl2;
    /**
     * 공고규격서URL3
     */
    @Field
    private String ntcespecdocurl3;
    /**
     * 공고규격서URL4
     */
    @Field
    private String ntcespecdocurl4;
    /**
     * 공고규격서URL5
     */
    @Field
    private String ntcespecdocurl5;
    /**
     * 공고규격서URL6
     */
    @Field
    private String ntcespecdocurl6;
    /**
     * 공고규격서URL7
     */
    @Field
    private String ntcespecdocurl7;
    /**
     * 공고규격서URL8
     */
    @Field
    private String ntcespecdocurl8;
    /**
     * 공고규격서URL9
     */
    @Field
    private String ntcespecdocurl9;
    /**
     * 공고규격서URL10
     */
    @Field
    private String ntcespecdocurl10;
    /**
     * 공고규격파일명1
     */
    @Field
    private String ntcespecfilenm1;
    /**
     * 공고규격파일명2
     */
    @Field
    private String ntcespecfilenm2;
    /**
     * 공고규격파일명3
     */
    @Field
    private String ntcespecfilenm3;
    /**
     * 공고규격파일명4
     */
    @Field
    private String ntcespecfilenm4;
    /**
     * 공고규격파일명5
     */
    @Field
    private String ntcespecfilenm5;
    /**
     * 공고규격파일명6
     */
    @Field
    private String ntcespecfilenm6;
    /**
     * 공고규격파일명7
     */
    @Field
    private String ntcespecfilenm7;
    /**
     * 공고규격파일명8
     */
    @Field
    private String ntcespecfilenm8;
    /**
     * 공고규격파일명9
     */
    @Field
    private String ntcespecfilenm9;
    /**
     * 공고규격파일명10
     */
    @Field
    private String ntcespecfilenm10;
    /**
     * 입찰이 유찰되는 경우 재공고 없이 다시 입찰(Y/N)
     */
    @Field
    private String rbidpermsnyn;
    /**
     * ????? ?? ??????? ??? ?? Y, ?????? ????? N
     */
    @Field
    private String prdctclsfclmtyn;
    /**
     * 물품분류로 투찰제한시 제조물품으로 제한할 지 여부. "Y"일 경우 투찰시 업체의 경쟁입찰참가자격등록증에 공고서상 물품분류가 제조물품으로 등록되어 있어야 투찰가능(Y/N)
     */
    @Field
    private String mnfctyn;
    /**
     * 예정가격결정방법명
     */
    @Field
    private String prearngprcedcsnmthdnm;
    /**
     * 총예가건수
     */
    @Field
    private String totprdprcnum;
    /**
     * 추첨예가건수
     */
    @Field
    private String drwtprdprcnum;
    /**
     * 배정예산금액
     */
    @Field
    private String asignbdgtamt;
    /**
     * 추정가격
     */
    @Field
    private String presmptprce;
    /**
     * 개찰장소
     */
    @Field
    private String opengplce;
    /**
     * 입찰공고상세URL
     */
    @Field
    private String bidntcedtlurl;
    /**
     * 입찰공고URL
     */
    @Field
    private String bidntceurl;
    /**
     * 입찰참가수수료납부여부
     */
    @Field
    private String bidprtcptfeepaymntyn;
    /**
     * 입찰참가수수료
     */
    @Field
    private String bidprtcptfee;
    /**
     * 입찰보증금납부여부
     */
    @Field
    private String bidgrntymnypaymntyn;
    /**
     * 채권자명
     */
    @Field
    private String crdtrnm;
    /**
     * ???????? ??? ?????????? [??????^??????(????????)^????(???????)],[??????^??????(????????)^????(???????)] ??
     */
    @Field
    private String purchsobjprdctlist;
    /**
     * 통합공고번호 입찰공고를 구분하는 번호로 입찰공고번호이며 형식은 년도(4)+월(2)+순번(5)
     */
    @Field
    private String untyntceno;
    /**
     * ???????? 1:????, 2:????, 3:??+????, 4:??????, 5:?? or ??, 6:?????????? ???
     */
    @Field
    private String cmmnspldmdmethdcd;
    /**
     * 공동수급방식명
     */
    @Field
    private String cmmnspldmdmethdnm;
    /**
     * 표준공고서URL
     */
    @Field
    private String stdntcedocurl;
    /**
     * 지사투찰허용여부
     */
    @Field
    private String brffcbidprcpermsnyn;
    /**
     * 지명경쟁여부
     */
    @Field
    private String dsgntcmptyn;
    /**
     * 예비가격재작성방법명
     */
    @Field
    private String rsrvtnprceremkngmthdnm;
    /**
     * 실적신청서접수방법명
     */
    @Field
    private String arsltappldocrcptmthdnm;
    /**
     * 실적신청서접수일시
     */
    @Field
    private String arsltappldocrcptdt;
    /**
     * 발주계획통합번호 업무구분코드(1)-업무유형코드(3)-발주년도(4)-기관코드(7)-발주계획순번(6) 로 구성됨
     */
    @Field
    private String orderplanuntyno;
    /**
     * 낙찰하한율
     */
    @Field
    private String sucsfbidlwltrate;
    /**
     * 등록일시 공고의 등록일시 “YYYY-MM-DD HH:MM:SS”
     */
    @Field
    private String rgstdt;
    /**
     * 사전규격등록번호
     */
    @Field
    private String bfspecrgstno;
    /**
     * 정보화사업여부
     */
    @Field
    private String infonizyn;
    /**
     * 낙찰방법코드 방위사업청 오픈API 연계데이터 포함
     */
    @Field
    private String sucsfbidmthdcd;
    /**
     * 낙찰방법명
     */
    @Field
    private String sucsfbidmthdnm;
    /**
     * 변경일시
     */
    @Field
    private String chgdt;
    /**
     * 연계기관명
     */
    @Field
    private String linkinsttnm;
    /**
     * 수요기관담당자이메일주소
     */
    @Field
    private String dminsttofclemailadrs;
    /**
     * 업종제한여부
     */
    @Field
    private String indstrytylmtyn;
    /**
     * 변경공고사유
     */
    @Field
    private String chgntcersn;
    /**
     * 재입찰개찰일시
     */
    @Field
    private String rbidopengdt;
    /**
     * 서비스번호
     */
    @Field
    private String service_no;
    /**
     * PQ신청서접수방법명
     */
    @Field
    private String pqappldocrcptmthdnm;
    /**
     * PQ신청서접수일시
     */
    @Field
    private String pqappldocrcptdt;
    /**
     * 예산금액
     */
    @Field
    private String bdgtamt;
    /**
     * 도급자설치관급자재금액
     */
    @Field
    private String contrctrcnstrtngovsplymtrlamt;
    /**
     * 공사현장지역명
     */
    @Field
    private String cnstrtsitergnnm;
    /**
     * 수정일자
     */
    @Field
    private String updt_dt;
    /**
     * 수정id
     */
    @Field
    private String updt_id;
    /**
     * 물품단가
     */
    @Field
    private String prdctuprc;
    /**
     * 분석여부
     */
    @Field
    private String indexyn;
    /**
     * 수집시간 
     */
    @Field
    private String reg_dt;
    /**
     * 공고일
     */
    @Field
    private String stdr_dt;
    /**
     * 검색키워드
     */
    @Field
    private String search_word;
    /**
     */
    @Field
    private String crawl_yn;
 

}