/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyStats.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.userMyStats.entity.UserMyStats;

/**
 * UserMyStats Mapper
 */
public interface UserMyStatsMapper {

    UserMyStats getUserMyStats(Map<String, Object> params);

    int selectUserMyStatsCnt(Map<String, Object> params);

    List<Map<String, Object>> selectUserMyStatsList(Map<String, Object> params);

    int insertUserMyStats(SimpleData simpleData);

    int updateUserMyStats(UserMyStats userMyStats);

    int deleteUserMyStats(SimpleData simpleData);

}
