/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfo.mapper;

import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.modules.accdntInfo.entity.AccdntInfo;

/**
 * AccdntInfo Mapper
 */
public interface AccdntInfoMapper {

    AccdntInfo getAccdntInfo(Map<String, Object> params);

    int selectAccdntInfoCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAccdntInfoList(Map<String, Object> params);

    int insertAccdntInfo(AccdntInfo accdntInfo);

    int updateAccdntInfo(AccdntInfo accdntInfo);

    int updateAccdntInfoDynamic(AccdntInfo accdntInfo);

    int deleteAccdntInfo(AccdntInfo accdntInfo);

}
