/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisInfo.service;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.analysisInfo.entity.AnalysisInfo;

import javax.servlet.http.HttpServletRequest;
import java.util.List;
import java.util.Map;

/**
 *  수집된 입찰정보에서 도로변경정보로 예측된  정보를 관리한다.  */
public interface AnalysisInfoService {

    AnalysisInfo getAnalysisInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getAnalysisInfoList(HttpServletRequest request) throws Exception;

    int saveAnalysisInfo(AnalysisInfo analysisInfo) throws Exception;

    int insertAnalysisInfo(AnalysisInfo analysisInfo) throws Exception;

    int updateAnalysisInfo(AnalysisInfo analysisInfo) throws Exception;

    int updateAnalysisInfoDynamic(AnalysisInfo analysisInfo) throws Exception;

    int deleteAnalysisInfo(AnalysisInfo analysisInfo) throws Exception;

	int updateAnalysisInfoKrris(SimpleData simpleData) throws Exception;;

    List<Map<String, Object>> getAnalysisInfoFileData(Map param) throws Exception;

    Map<String, Object> getAnalysisInfoFileDataList(Map param) throws Exception;

	Map<String, Object> getAnalysisInfoFileDataListMulti(Map param) throws Exception;
}
