/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/domain/Entity.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfo.entity;

import java.math.BigDecimal;
import java.time.LocalDate;

import lombok.Data;

/**
 *  유고정보(공사/사고)를 관리한다.  */

@Data
public class AccdntInfo {

    /**
     * 유고정보번호
     */
    private Long id;
    /**
     * 공사사고구분
     */
    private String cntrwkAcdntSe;
    /**
     * 고유식별번호
     */
    private String esntlIdntfcNo;
    /**
     * 공사사고유형
     */
    private String cntrwkAcdntTy;
    /**
     * 차로차단방법
     */
    private String cartrkIntrcpMth;
    /**
     * 차단된차로수
     */
    private Integer blockLaneCnt;
    /**
     * 공사시작일
     */
    private String cntrwkBgnde;
    /**
     * 공사종료일
     */
    private String cntrwkEndde;
    /**
     * 공사실제개시시간
     */
    private String cntrwkRealBeginTime;
    /**
     * 공사실제종료시간
     */
    private String cntrwkRealEndTime;
    /**
     * 돌발상황지속여부
     */
    private String outbrkSittnCntncAt;
    /**
     * 상황정보메시지
     */
    private String sittnInfoMssage;
    /**
     * X좌표
     */
    private BigDecimal utmkX;
    /**
     * Y좌표
     */
    private BigDecimal utmkY;
    /**
     * 등록일시
     */
    private LocalDate registDt;
    /**
     * WKT 변환좌표 (EPSG3857)
     */
    private String wktGeom;

    public boolean hasPk() {
        return id != null;
    }

}