/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/controller/Controller.e.vm.java
 */
package kr.or.lx.rcic.modules.userMyArea.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.frmwrk.web.BaseController;
import kr.or.lx.rcic.modules.userMyArea.entity.UserMyArea;
import kr.or.lx.rcic.modules.userMyArea.service.UserMyAreaService;

import lombok.extern.slf4j.Slf4j;

/**
 *  나의관심지역  */
@Controller
@Slf4j
@RequestMapping("/rcic")
public class UserMyAreaController extends BaseController {

    @Autowired
    private UserMyAreaService userMyAreaService;

    // api

    /**
     * 단건 조회
     */
    @RequestMapping("/userMyArea/getUserMyArea")
    @ResponseBody
    public UserMyArea getUserMyArea(HttpServletRequest request, @RequestParam Map params) throws Exception {
        SimpleData simpleData = getSimpleData(request);
        log.debug("simpleData: {}", simpleData);
        return userMyAreaService.getUserMyArea(simpleData);
    }

    /**
     * 목록 조회
     */
    @RequestMapping("/userMyArea/getUserMyAreaList")
    @ResponseBody
    public Map<String, Object> getUserMyAreaList(HttpServletRequest request) throws Exception {
        return userMyAreaService.getUserMyAreaList(request);
    }

    /**
     * 등록
     */
    @PostMapping("/userMyArea/insertUserMyArea")
    @ResponseBody
    public int insertUserMyArea(HttpServletRequest request) throws Exception {
        return userMyAreaService.insertUserMyArea(getSimpleData(request));
    }

    /**
     * 수정
     */
    @PostMapping("/userMyArea/updateUserMyArea")
    @ResponseBody
    public int updateUserMyArea(HttpServletRequest request, @RequestBody UserMyArea userMyArea) throws Exception {
        return userMyAreaService.updateUserMyArea(userMyArea);
    }

    /**
     * 동적 수정
     */
    @PostMapping("/userMyArea/patchUserMyArea")
    @ResponseBody
    public int patchUserMyArea(HttpServletRequest request, @RequestBody UserMyArea userMyArea) throws Exception {
        return userMyAreaService.updateUserMyArea(userMyArea);
    }

    /**
     * 삭제
     */
    @PostMapping("/userMyArea/deleteUserMyArea")
    @ResponseBody
    public int deleteUserMyArea(HttpServletRequest request) throws Exception {
        return userMyAreaService.deleteUserMyArea(getSimpleData(request));
    }

}
