/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.accdntInfo.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.modules.accdntInfo.entity.AccdntInfo;
import kr.or.lx.rcic.modules.accdntInfo.mapper.AccdntInfoMapper;
import kr.or.lx.rcic.modules.accdntInfo.service.AccdntInfoService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  유고정보(공사/사고)를 관리한다.  */
@Service
@Slf4j
public class AccdntInfoServiceImpl implements AccdntInfoService {

    @Autowired
    private AccdntInfoMapper accdntInfoMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public AccdntInfo getAccdntInfo(Map<String, Object> params) throws Exception {
        return accdntInfoMapper.getAccdntInfo(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getAccdntInfoList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = accdntInfoMapper.selectAccdntInfoCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = accdntInfoMapper.selectAccdntInfoList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveAccdntInfo(AccdntInfo accdntInfo) throws Exception {

        // 저장 권한 검사 등..

        if (accdntInfo.hasPk()) {
            // 수정
            return updateAccdntInfo(accdntInfo);
        } else {
            // 신규 등록
            return insertAccdntInfo(accdntInfo);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertAccdntInfo(AccdntInfo accdntInfo) throws Exception {
        return accdntInfoMapper.insertAccdntInfo(accdntInfo);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateAccdntInfo(AccdntInfo accdntInfo) throws Exception {
        return accdntInfoMapper.updateAccdntInfo(accdntInfo);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateAccdntInfoDynamic(AccdntInfo accdntInfo) throws Exception {
        return accdntInfoMapper.updateAccdntInfoDynamic(accdntInfo);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteAccdntInfo(AccdntInfo accdntInfo) throws Exception {
        return accdntInfoMapper.deleteAccdntInfo(accdntInfo);
    }

}
