/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/controller/Controller.e.vm.java
 */
package kr.or.lx.rcic.modules.admin.rest;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.frmwrk.web.BaseController;
import kr.or.lx.rcic.modules.user.entity.AuthDtl;
import kr.or.lx.rcic.modules.user.service.AuthDtlService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 *  권한별 상세정보를 관리한다.
*/
@Controller
@Slf4j
@RequestMapping("/rcic")
public class AuthDtlController extends BaseController {

    @Autowired
    private AuthDtlService authDtlService;

    // api

    /**
     * 단건 조회
     */
    @RequestMapping("/authDtl/getAuthDtl")
    @ResponseBody
    public AuthDtl getAuthDtl(HttpServletRequest request, @RequestParam Map params) throws Exception {
        SimpleData simpleData = getSimpleData(request);
        return authDtlService.getAuthDtl(simpleData);
    }

    /**
     * 목록 조회
     */
    @RequestMapping("/authDtl/getAuthDtlList")
    @ResponseBody
    public Map<String, Object> getAuthDtlList(HttpServletRequest request) throws Exception {
        return authDtlService.getAuthDtlList(request);
    }

    /**
     * 등록
     */
    @PostMapping("/authDtl/insertAuthDtl")
    @ResponseBody
    public int insertAuthDtl(HttpServletRequest request, @RequestBody AuthDtl authDtl) throws Exception {
        return authDtlService.saveAuthDtl(authDtl);
    }

    /**
     * 수정
     */
    @PostMapping("/authDtl/updateAuthDtl")
    @ResponseBody
    public int updateAuthDtl(HttpServletRequest request, @RequestBody AuthDtl authDtl) throws Exception {
        return authDtlService.saveAuthDtl(authDtl);
    }

    /**
     * 동적 수정
     */
    @PostMapping("/authDtl/patchAuthDtl")
    @ResponseBody
    public int patchAuthDtl(HttpServletRequest request, @RequestBody AuthDtl authDtl) throws Exception {
        return authDtlService.saveAuthDtl(authDtl);
    }

    /**
     * 삭제
     */
    @PostMapping("/authDtl/deleteAuthDtl")
    @ResponseBody
    public int deleteAuthDtl(HttpServletRequest request, @RequestBody AuthDtl authDtl) throws Exception {
        return authDtlService.deleteAuthDtl(authDtl);
    }

}
