/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/impl/ServiceImpl.e.vm.java
 */
package kr.or.lx.rcic.modules.user.service.impl;

import kr.co.timosoft.util.PaginationUtil;
import kr.or.lx.rcic.egovframework.cmmn.util.EgovMessageSource;
import kr.or.lx.rcic.frmwrk.util.CmmnUtil;
import kr.or.lx.rcic.modules.user.entity.AuthDtl;
import kr.or.lx.rcic.modules.user.mapper.AuthDtlMapper;
import kr.or.lx.rcic.modules.user.service.AuthDtlService;
import lombok.extern.slf4j.Slf4j;
import net.sf.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *  권한별 상세정보를 관리한다.  */
@Service
@Slf4j
public class AuthDtlServiceImpl implements AuthDtlService {

    @Autowired
    private AuthDtlMapper authDtlMapper;

    @Resource(name = "egovMessageSource")
    EgovMessageSource egovMessageSource;

    /**
     * 단건 조회
     */
    @Override
    public AuthDtl getAuthDtl(Map<String, Object> params) throws Exception {
        return authDtlMapper.getAuthDtl(params);
    }

    /**
     * 목록 조회
     */
    @Override
    public Map<String, Object> getAuthDtlList(HttpServletRequest request) throws Exception {

        HashMap<String, Object> resultMap = new HashMap<String, Object>();
        HashMap<String, Object> retMap = new HashMap<String, Object>();
        resultMap.put("message", "success");
        String strParamList = CmmnUtil.deXss(CmmnUtil.checkNull(request.getParameter("paramList"), ""));
        if (strParamList.equals("")) {
            retMap.put("message", "failure");
            retMap.put("result", egovMessageSource.getMessage("_REQUIRED_MSG_REPEAT"));
            return retMap;
        }

        JSONArray paramList = JSONArray.fromObject(strParamList);
        HashMap<String, Object> param = new HashMap<String, Object>();
        param = CmmnUtil.convertJsonToObject(CmmnUtil.checkNull(paramList.getJSONObject(0), ""));

        int listCnt = param.get("listCnt") == null ? 10 : Integer.parseInt(String.valueOf(param.get("listCnt")));
        int currPage = param.get("currPage") == null ? 1 : Integer.parseInt(String.valueOf(param.get("currPage")));

        param.put("listCnt", listCnt);
        param.put("currPage", currPage);

        int cnt = authDtlMapper.selectAuthDtlCnt(param);
        int maxPageCnt = PaginationUtil.maxPageCnt(cnt, listCnt);
        List<Map<String, Object>> list = authDtlMapper.selectAuthDtlList(param);

        resultMap.put("maxPageCnt", maxPageCnt);
        resultMap.put("list", list);

        return resultMap;
    }

    /**
     * 저장
     */
    @Override
    @Transactional
    public int saveAuthDtl(AuthDtl authDtl) throws Exception {

        // 저장 권한 검사 등..

        if (authDtl.hasPk()) {
            // 수정
            return updateAuthDtl(authDtl);
        } else {
            // 신규 등록
            return insertAuthDtl(authDtl);
        }
    }

    /**
     * 등록
     */
    @Override
    @Transactional
    public int insertAuthDtl(AuthDtl authDtl) throws Exception {

        if (authDtlMapper.existAuthDtl(authDtl)) {
            return authDtlMapper.updateAuthDtlDynamic(authDtl);
        }

        return authDtlMapper.insertAuthDtl(authDtl);
    }

    /**
     * 수정
     */
    @Override
    @Transactional
    public int updateAuthDtl(AuthDtl authDtl) throws Exception {
        return authDtlMapper.updateAuthDtl(authDtl);
    }

    /**
     * 동적 수정
     */
    @Override
    @Transactional
    public int updateAuthDtlDynamic(AuthDtl authDtl) throws Exception {
        return authDtlMapper.updateAuthDtlDynamic(authDtl);
    }

    /**
     * 삭제
     */
    @Override
    @Transactional
    public int deleteAuthDtl(AuthDtl authDtl) throws Exception {
        return authDtlMapper.deleteAuthDtl(authDtl);
    }

}
