/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.snsAccountInfo.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import kr.or.lx.rcic.modules.snsAccountInfo.entity.SnsAccountInfo;

/**
 *  수집대상이 되는 SNS 트위터 계정정보를 관리한다.  */
public interface SnsAccountInfoService {

    SnsAccountInfo getSnsAccountInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getSnsAccountInfoList(HttpServletRequest request) throws Exception;

    int saveSnsAccountInfo(SnsAccountInfo snsAccountInfo) throws Exception;

    int insertSnsAccountInfo(SnsAccountInfo snsAccountInfo) throws Exception;

    int updateSnsAccountInfo(SnsAccountInfo snsAccountInfo) throws Exception;

    int updateSnsAccountInfoDynamic(SnsAccountInfo snsAccountInfo) throws Exception;

    int deleteSnsAccountInfo(SnsAccountInfo snsAccountInfo) throws Exception;

    int changeUseYnSnsAccountInfo(SnsAccountInfo snsAccountInfo) throws Exception;

}
