/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.service;

import kr.or.lx.rcic.modules.dataapi.entity.ApiBlockInfo;

import java.util.Map;

/**
 *  API 사용자의 차단정보를 관리한다.  */
public interface ApiBlockInfoService {

    ApiBlockInfo getApiBlockInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getApiBlockInfoList(Map<String, Object> params) throws Exception;

    int saveApiBlockInfo(ApiBlockInfo apiBlockInfo) throws Exception;

    int insertApiBlockInfo(ApiBlockInfo apiBlockInfo) throws Exception;

    int updateApiBlockInfo(ApiBlockInfo apiBlockInfo) throws Exception;

    int updateApiBlockInfoDynamic(ApiBlockInfo apiBlockInfo) throws Exception;

    int deleteApiBlockInfo(ApiBlockInfo apiBlockInfo) throws Exception;

}
