/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.service;

import kr.or.lx.rcic.modules.dataapi.entity.ApiProvdInfo;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 *  API로 제공되는 정보를 관리한다.  */
public interface ApiProvdInfoService {

    ApiProvdInfo getApiProvdInfo(Map<String, Object> params) throws Exception;

    Map<String, Object> getApiProvdInfoList(HttpServletRequest request) throws Exception;

    int saveApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception;

    int insertApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception;

    int updateApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception;

    int updateApiProvdInfoDynamic(ApiProvdInfo apiProvdInfo) throws Exception;

    int deleteApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception;

    int changeUseYnApiProvdInfo(ApiProvdInfo apiProvdInfo) throws Exception;

}
