/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/service/Service.e.vm.java
 */
package kr.or.lx.rcic.modules.dataapi.service;

import kr.or.lx.rcic.modules.dataapi.entity.ApiUseDtl;

import javax.servlet.http.HttpServletRequest;
import java.util.Map;

/**
 *  API를 통해 제공된 사용내역을 관리한다.  */
public interface ApiUseDtlService {

    ApiUseDtl getApiUseDtl(Map<String, Object> params) throws Exception;

    Map<String, Object> getApiUseDtlList(HttpServletRequest request) throws Exception;

    int saveApiUseDtl(ApiUseDtl apiUseDtl) throws Exception;

    int insertApiUseDtl(ApiUseDtl apiUseDtl) throws Exception;

    int updateApiUseDtl(ApiUseDtl apiUseDtl) throws Exception;

    int updateApiUseDtlDynamic(ApiUseDtl apiUseDtl) throws Exception;

    int deleteApiUseDtl(ApiUseDtl apiUseDtl) throws Exception;

}
