/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-rcic:src/main/java/mapper/Mapper.e.vm.java
 */
package kr.or.lx.rcic.modules.analysisLocHist.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import kr.or.lx.rcic.frmwrk.util.SimpleData;
import kr.or.lx.rcic.modules.analysisLocHist.entity.AnalysisLocHist;

/**
 * AnalysisLocHist Mapper
 */
public interface AnalysisLocHistMapper {

    AnalysisLocHist getAnalysisLocHist(Map<String, Object> params);

    int selectAnalysisLocHistCnt(Map<String, Object> params);

    List<Map<String, Object>> selectAnalysisLocHistList(Map<String, Object> params);

    int insertAnalysisLocHist(SimpleData simpleData);

    int updateAnalysisLocHist(AnalysisLocHist analysisLocHist);
    
    int updateChangeLocation(SimpleData simpleData);

    int updateAnalysisLocHistDynamic(AnalysisLocHist analysisLocHist);

    int deleteAnalysisLocHist(AnalysisLocHist analysisLocHist);

	List<Map<String, Object>> selectAnalysisLocHistNew(HashMap<String, Object> param);
	
	String getChnage_yn(String resultno);

}
